### ISSUE TITLE
Norwood & Brixton food bank is not listed in the Dulwich & West Norwood constituency

### ISSUE THREAD

**Issue by adamalton** [givefood/givefood#182] opened 2020-12-30 10:36 UTC
Steps to reproduce:

1. Go to the page for [Norwood & Brixton food bank](https://www.givefood.org.uk/needs/at/norwood-brixton/).
2. Note the 3 locations, SE27 0HS, SW9 8AH and SW2 3BH.
3. Take each of those post codes and enter each one in turn into the search box on the [/needs/in/constituencies/](https://www.givefood.org.uk/needs/in/constituencies/) page. The resulting redirects are:
    - SE27 0HS => [Dulwich & West Norwood](https://www.givefood.org.uk/needs/in/constituency/dulwich-and-west-norwood/)
    - SW9 8AH => [Vauxhall](https://www.givefood.org.uk/needs/in/constituency/vauxhall/)
    - SW2 3BH => [Streatham](https://www.givefood.org.uk/needs/in/constituency/streatham/)

Observed result:

The Vauxhall and Streatham constituency pages both list the Norwood & Brixton food bank, but the Dulwich & West Norwood page does not. See [Screenshot](https://user-images.githubusercontent.com/270255/103345900-814a3b00-4a8a-11eb-8281-6866b64d84f0.png)

Expected result:

The Norwood & Brixton food bank is listed on all three constituency pages.

I'm guessing that this is going to be an annoying edge case/anomaly caused by the fact that it's a single food bank with three locations. But I'm thinking it would be better for it to be over-listed than under-listed.

**Comment by jasoncartwright** [comment] 2020-12-30 11:38
Thank you for the excellent bug report. This data was certainly incorrect. That's embarrassing and not good enough.

I've fixed the data (which also as a side effect fixed the broken MP photo). You can see this change here...

https://github.com/givefood/data/commit/c0d70ca06f0f426779d36d34430af34a37d3e74a#diff-32d55049a3e05fc522fd047ac8e10e13b6c2ee2ffc46bfafb30408554a9e92a4

The root cause of the issue is the incorrect assumption that when a food bank's location is changed that the parliamentary constituency it's in won't change. This is assumption was made for speed.

You can see this here. If the food bank already has a parliamentary_constituency set it won't go and do the lookup to the slow external API...

https://github.com/givefood/givefood/blob/master/givefood/models.py#L206

The quickfix will be to remember to check the parliamentary constituency on the rare occasion a food bank changes location. This should also be fixed in the code (#184). We'll also audit all our political data in the new year (#183)

**Closed by jasoncartwright** 2020-12-30 11:38 UTC

**Comment by adamalton** [comment] 2020-12-30 11:47
Nice! A rapid fix with some git scraping thrown in! 💥
